{{- if .Values.remotellm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: llm-credentials
  namespace: {{ .Values.namespacePrefix }}-{{ .Values.username }}
  labels:
    app.kubernetes.io/component: llm-credentials
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  LLM_API_KEY: {{ .Values.remotellm.apiToken | b64enc | quote }}
  LLM_BASE_URL: {{ .Values.remotellm.url | b64enc | quote }}
  LLM_MODEL: {{ .Values.remotellm.id | b64enc | quote }}
{{- end }}
