---
purpose: development

# Enable Showroom dev mode for faster content iteration
ocp4_workload_showroom_antora_enable_dev_mode: "true"

__meta__:
  access_control:
    allow_groups:
    - rhpds-devs
  deployer:
    scm_ref: main
