---
apiVersion: v2
description: A Helm chart for minio 🐈
name: minio
version: 1.0.0
home: https://github.com/rhpds/agentops-in-prod-automation
icon: https://cdn-icons-png.flaticon.com/512/2676/2676169.png 
maintainers:
  - name: rcarrata
